#!/bin/bash

function DO_REBUILD_WITH {
  while read line; do
    FROM=$(echo $line | cut -d' ' -f1)
    TO=$(echo $line | cut -d' ' -f2)

    add_mapping $FROM $TO
  done < $1
}

if [ -f /etc/forwarding/mapping.conf ]; then
  DO_REBUILD_WITH /etc/forwarding/mapping.conf
fi

TEMP_FILE=`mktemp /tmp/XXXXXXXXXX`
echo $EMAIL_MAPPINGS|sed -r "s:,:\n:g"|sed -r "s:\:: :g" > $TEMP_FILE
DO_REBUILD_WITH $TEMP_FILE
trap "rm -f $TEMP_FILE" 0 1 2 5 15

